[package]
name = "storage"
version = "0.1.0"
edition.workspace = true

[dev-dependencies]
serial_test = "3.2.0"

[dependencies]
crossbeam-skiplist = "0.1"
thiserror = "2.0.0"
dashmap = "6.1"
serde = { version = "1.0", features = ["derive"] }
postcard = { version = "1.1.1", features = ["alloc"] }
crc32fast = "1.4.2"
bytes = "1.10.0"
chrono = "0.4.40"
crossbeam-epoch = "0.9"
common = { path = "../common" }

[lints]
workspace = true
